### ISSUE TITLE
AttributeError registry has no attribute 'generate_model_name' (definition_collection)

### ISSUE THREAD

**Issue by arnaudbos** [spiral-project/daybed#92]
Edit: On `dev` branch!

I'm having this issue when POSTing on `/definitions/`:

```
2014-01-02 02:11:15,505 ERROR [waitress][Dummy-2] Exception when serving /definitions/
Traceback (most recent call last):
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/waitress/channel.py", line 337, in service
    task.service()
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/waitress/task.py", line 173, in service
    self.execute()
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/waitress/task.py", line 392, in execute
    app_iter = self.channel.server.application(env, start_response)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/router.py", line 272, in __call__
    response = self.invoke_subrequest(request, use_tweens=True)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/router.py", line 247, in invoke_subrequest
    response = handle_request(request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/tweens.py", line 40, in excview_tween
    response = view_callable(exc, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 385, in viewresult_to_response
    result = view(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/tweens.py", line 21, in excview_tween
    response = handler(request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/router.py", line 163, in handle_request
    response = view_callable(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 596, in __call__
    return view(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 329, in attr_view
    return view(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 305, in predicate_wrapper
    return view(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 355, in rendered_view
    result = view(context, request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/pyramid-1.5a3-py2.7.egg/pyramid/config/views.py", line 501, in _requestonly_view
    response = view(request)
  File "/home/abos/Lab/SPIRAL_daybed/local/lib/python2.7/site-packages/cornice-0.16.2-py2.7.egg/cornice/service.py", line 514, in wrapper
    response = view_(request)
  File "/home/abos/Lab/SPIRAL_daybed/daybed/views/definition_collection.py", line 22, in post
    model_name = request.registry.generate_model_name(request)
AttributeError: 'Registry' object has no attribute 'generate_model_name'
```

Also I'm wondering:

I don't get the (functional) difference between `definition_collection.post` and `definition.put_definition`.

The former seems to be a different version of the later, more "HTTP compliant" (201 Created status).

Is that all the motivation for this separate endpoint or is there more to that? Maybe this is discussed in another issue?

Thanks!

**Comment by leplatrem** [comment]
Regarding the `AttributeError`, I can't explain why this was contributed in https://github.com/spiral-project/daybed/commit/e56cd08c7678d32f1472cf3323c17ed15fb1c594 and not present here anymore.
This is big, and we should definitely fixed it. (/cc @ametaireau @Natim)

Regarding the two services or end points in Cornice, I can't say much myself about this, but I guess `POST` was meant to create items on a collection, and `PUT` to update existing ones.

I would definitely appreciate if a clean-up was done around all that. Unfortunately we've all been waiting for the huge changes yet to be merged from `ACL` branch...

**Comment by leplatrem** [comment]
Well, I read the changes introduced in 85827ee32e6702d08045035d8fd3a95018e7b3f4 and it looks like that in `dev` branch, you should use `/models` end-points, and definitions views should be removed.

It seems that @ametaireau forgot to completely get rid of _definition_ notions when introducing _models_. (He removed a single test too, that makes dev pass with this issue).

**Comment by arnaudbos** [comment]
Got it, I'm using the `models` endpoints at the moment and it works just fine.

**Comment by almet** [comment]
that's right, we should definitely remove this.

**Comment by Natim** [comment]
Should be fixed by now.
